In [52]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [53]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/gdrive/My Drive/전산통계/원본 자료/wisc_bc_data.csv")
print(df.head())

         id diagnosis  ...  symmetry_worst  dimension_worst
0  87139402         B  ...          0.2827          0.06771
1   8910251         B  ...          0.2940          0.07587
2    905520         B  ...          0.2998          0.07881
3    868871         B  ...          0.2102          0.06784
4   9012568         B  ...          0.2487          0.06766

[5 rows x 32 columns]


In [54]:
df['symmetry_worst'].sum() / n_samples

0.2900755711775044

In [55]:
df['symmetry_worst'].mean()

0.29007557117750443

## 데이터 전처리

In [56]:
df.shape

(569, 32)

In [57]:
n_samples, n_features = df.shape

In [58]:
feature = list(df.columns)
feature[:5]

['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean']

In [59]:
data_feature = feature[2:]
data_feature[:5]

['radius_mean',
 'texture_mean',
 'perimeter_mean',
 'area_mean',
 'smoothness_mean']

In [60]:
data = df[data_feature]
data = data.values # id, diagnosis 제외한 변수들을 array 형태로 변경

In [61]:
data[:5]

array([[1.232e+01, 1.239e+01, 7.885e+01, 4.641e+02, 1.028e-01, 6.981e-02,
        3.987e-02, 3.700e-02, 1.959e-01, 5.955e-02, 2.360e-01, 6.656e-01,
        1.670e+00, 1.743e+01, 8.045e-03, 1.180e-02, 1.683e-02, 1.241e-02,
        1.924e-02, 2.248e-03, 1.350e+01, 1.564e+01, 8.697e+01, 5.491e+02,
        1.385e-01, 1.266e-01, 1.242e-01, 9.391e-02, 2.827e-01, 6.771e-02],
       [1.060e+01, 1.895e+01, 6.928e+01, 3.464e+02, 9.688e-02, 1.147e-01,
        6.387e-02, 2.642e-02, 1.922e-01, 6.491e-02, 4.505e-01, 1.197e+00,
        3.430e+00, 2.710e+01, 7.470e-03, 3.581e-02, 3.354e-02, 1.365e-02,
        3.504e-02, 3.318e-03, 1.188e+01, 2.294e+01, 7.828e+01, 4.248e+02,
        1.213e-01, 2.515e-01, 1.916e-01, 7.926e-02, 2.940e-01, 7.587e-02],
       [1.104e+01, 1.683e+01, 7.092e+01, 3.732e+02, 1.077e-01, 7.804e-02,
        3.046e-02, 2.480e-02, 1.714e-01, 6.340e-02, 1.967e-01, 1.387e+00,
        1.342e+00, 1.354e+01, 5.158e-03, 9.355e-03, 1.056e-02, 7.483e-03,
        1.718e-02, 2.198e-03, 1.241e

In [62]:
target = df['diagnosis'].values # diagnosis array 형태로 변경

In [63]:
target[:5]

array(['B', 'B', 'B', 'B', 'B'], dtype=object)

In [64]:
target_name = list(df['diagnosis'].unique()) # ['B', 'M']

## KNN 이용한 학습

In [65]:
from sklearn import neighbors
X, y = data, target
knn = neighbors.KNeighborsClassifier(n_neighbors=3)
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [66]:
test = []
for val in data_feature:
    test.append(df[val].mean())

test

[14.127291739894558,
 19.28964850615113,
 91.96903339191556,
 654.8891036906854,
 0.09636028119507911,
 0.10434098418277687,
 0.08879931581722318,
 0.048919145869947216,
 0.18116186291739908,
 0.06279760984182774,
 0.4051720562390159,
 1.2168534270650258,
 2.8660592267135323,
 40.33707908611605,
 0.007040978910369067,
 0.02547813884007029,
 0.03189371634446398,
 0.011796137082601068,
 0.02054229876977152,
 0.0037949038664323374,
 16.269189806678384,
 25.677223198594024,
 107.26121265377854,
 880.5831282952557,
 0.1323685940246046,
 0.25426504393673083,
 0.2721884833040422,
 0.11460622319859401,
 0.29007557117750443,
 0.08394581722319862]

In [71]:
print(knn.predict([test]))

['B']


## 표준화 하기

In [72]:
from sklearn.preprocessing import StandardScaler
Z = StandardScaler().fit_transform(X)
Z

array([[-0.51329651, -1.60559452, -0.54037561, ..., -0.31513306,
        -0.11932056, -0.89972108],
       [-1.00180093, -0.07903849, -0.93456583, ..., -0.53820271,
         0.06348865, -0.44752801],
       [-0.87683468, -0.57237672, -0.8670139 , ..., -0.61357437,
         0.15731992, -0.28460551],
       ...,
       [ 0.32738551,  0.72612674,  0.28631171, ...,  0.12171802,
         0.44366709,  0.7633076 ],
       [ 0.11437486, -1.23559085,  0.07788929, ..., -0.11733956,
        -0.47685008, -0.32395074],
       [ 2.05703196, -0.97495933,  2.03195239, ...,  1.24848623,
        -0.27624528,  0.15040866]])

## 모델 정확도 검증

In [78]:
from sklearn.model_selection import train_test_split
Z_train, Z_test, y_train, y_test = train_test_split(Z, y, test_size = 0.3)

In [77]:
#training dataset
Z_train.shape, y_train.shape

((398, 30), (398,))

In [79]:
import math
math.sqrt(398)

19.949937343260004

In [80]:
knn = neighbors.KNeighborsClassifier(n_neighbors = 19)
knn.fit(Z_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=19, p=2,
                     weights='uniform')

In [82]:
pred = knn.predict(Z_test)

In [83]:
pred

array(['B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'M', 'B',
       'B', 'M', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M',
       'M', 'B', 'M', 'B', 'M', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M',
       'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'M', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'M',
       'B', 'M', 'M', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B',
       'M', 'M', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M',
       'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B', 'B', 'M',
       'B', 'B'], dtype=object)

In [85]:
from sklearn import metrics
metric19 = metrics.confusion_matrix(y_test, pred)
print(metric19)

[[101   2]
 [  9  59]]


In [89]:
import numpy as np
np.sum(metric19)

171

In [94]:
accuracy = (metric19[0,0] + metric19[1,1]) / np.sum(metric19)
error_rate = 1 - accuracy
print(accuracy, error_rate)

0.935672514619883 0.06432748538011701


## 최적 n사이즈 찾기

In [96]:
def accuracy(metric):
    import numpy as np

    length = len(metric)
    correct = 0
    for i in range(length):
        correct += metric[i, i]
    
    return correct / np.sum(metric) 

In [103]:
best_n = None
best_acc = 0

for i in range(1,100,2):
    knn = neighbors.KNeighborsClassifier(n_neighbors = i)
    knn.fit(Z_train, y_train)
    pred = knn.predict(Z_test)
    metric = metrics.confusion_matrix(y_test, pred)
    _tmp = accuracy(metric)
    if _tmp > best_acc:
        best_acc = _tmp
        best_n = i

print("(n=%s)일 때, 최적의 Accuracy(%0.4f)와 Error Rate(%0.4f) 갖는다!" % (best_n, best_acc, 1-best_acc))

(n=7)일 때, 최적의 Accuracy(0.9591)와 Error Rate(0.0409) 갖는다!
